services:
  app:
    build: .
    container_name: planeja_facil_api
    ports:
      - "8000:8000"
    volumes:
      - .:/app
        # mount current '.' directory to /app in the conteiner
        # app main application code, API fastAPI running with uvicorn
      - ./secrets:/secrets:ro # Read-only mount for secrets (add if app needs Firebase)

    env_file:
      - .env
    command: uvicorn main:app --host 0.0.0.0 --port 8000 #to allow external access

  auth_template:
    build:
      context: .
      dockerfile: services/auth_template/Dockerfile
    container_name: planeja_facil_auth_template
    ports:
      - "8001:8001"
    volumes:
      - ./services/auth_template:/app
      - ./shared:/app/shared # shared config to firebase, to be accessed by microservice users
      - ./secrets:/secrets:ro # Mount secrets of host in /secrets in conteiner
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    env_file:
      - .env
    command: uvicorn main:app --host 0.0.0.0 --port 8001

  blocks_phases_resources:
    build:
      context: .
      dockerfile: services/blocks_phases_resources/Dockerfile
    container_name: planeja_facil_blocks_phases
    ports:
      - "8002:8002"
    volumes:
      - ./services/blocks_phases_resources:/app
      - ./shared:/app/shared
      - ./secrets:/secrets:ro
    env_file:
      - .env
    command: uvicorn main:app --host 0.0.0.0 --port 8002

  production_orders:
    build:
      context: .
      dockerfile: services/production_orders/Dockerfile
    container_name: planeja_facil_production_orders
    ports:
      - "8003:8003"
    volumes:
      - ./services/production_orders:/app
      - ./shared:/app/shared
      - ./secrets:/secrets:ro
    env_file:
      - .env
    command: uvicorn main:app --host 0.0.0.0 --port 8003
